# Generated by Django 2.0.3 on 2018-03-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20180316_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecordsignalsnippet',
            name='destination',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='callrecordsignalsnippet',
            name='source',
            field=models.CharField(blank=True, default='', max_length=11),
        ),
    ]
