# Generated by Django 2.0.3 on 2018-04-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecordSignal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordId', models.IntegerField(default=0)),
                ('callType', models.CharField(default='', max_length=5)),
                ('call_id', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField()),
                ('source', models.CharField(blank=True, default='', max_length=11)),
                ('destination', models.CharField(blank=True, default='', max_length=11)),
            ],
            options={
                'ordering': ('recordId',),
            },
        ),
    ]
