# Generated by Django 2.0.3 on 2018-04-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signaling', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callrecordsignal',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='callrecordsignal',
            name='recordId',
        ),
        migrations.AlterField(
            model_name='callrecordsignal',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
