# Generated by Django 2.0.3 on 2018-03-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecordSignalSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordId', models.IntegerField(default=0)),
                ('callType', models.CharField(default='', max_length=5)),
                ('call_id', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='', max_length=9)),
                ('destination', models.CharField(default='', max_length=9)),
            ],
            options={
                'ordering': ('recordId',),
            },
        ),
    ]
