# Generated by Django 2.0.3 on 2018-03-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecordsignalsnippet',
            name='destination',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='callrecordsignalsnippet',
            name='source',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
    ]
