# Generated by Django 2.0.3 on 2018-03-19 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20180316_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecordsignalsnippet',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
