# Generated by Django 2.0.3 on 2018-03-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_auto_20180319_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecordsignalsnippet',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
