# Generated by Django 2.0.3 on 2018-03-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_auto_20180319_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecordsignalsnippet',
            name='timestamp',
            field=models.DateTimeField(blank=True),
        ),
    ]
